### ISSUE TITLE
Feature request: Multiple stopIds or quays in the same display position/instance

### ISSUE THREAD

**Issue by marviks** [Arve/MMM-Entur-tavle#10]
I live close to two bus stops each witch different routes to usually the same destination. Being able to include two stops in the same instance and get them time sorted would have been display space efficient, considering that I have to occupy two positioning-slots to get both of the stops on display the way things are right now.

**Comment by Arve** [comment]
While this is possible - but not ideal -  to do with Entur's APIs, I can't make any promises about _when_ I get around to it., thanks to work commitments.

To elaborate on "Not ideal" - while Entur has an API for querying multiple stopPlaces in one go, they aren't merged, so I'll have to write new code to manually merge and sort the results. The net result of this is that I'd have to make somewhat of a rewrite to accomodate this new query pattern, and the original code is a tad naive on how it goes about this.

**Comment by enrarot** [comment]
I would also appreciate the possibility to have multiple stops combined. Any progress or thoughts; @Arve ?

**Comment by Arve** [comment]
I must have the worst response time for issues, but due to the greatly added complexity, I won't add either of these features for now.
