### ISSUE TITLE
Can you provide an example for how to specify quay?

### ISSUE THREAD

**Issue by harald25** [Arve/MMM-Entur-tavle#12]
I'm not able to understand how to specify the quay ID. Can you give an example?
I would appreciate that a lot :)

**Comment by oisteink** [comment]
Easy enough - you type Quay stopType field, and the QuayNumber in the stopId field

config: {
	stopId: '1094',
	stopType: 'Quay',
	numResults: 5,
	showName: true,
	highlightRealtime: true,
	delay: [5, 'minutes']
}

From https://developer.entur.org/stops-and-timetable-data:
> The stops referred to are defined in the national stop registry. It's possible to log in with the "guest"/"guest"-account to view the content or use the geocoder, or NeTEx dump to extract what you may be looking for.

You find the national stop registry at https://stoppested.entur.org/
