### ISSUE TITLE
Error in example config

### ISSUE THREAD

**Issue by alistairspalding** [Arve/MMM-Entur-tavle#14]
In the example config in the README:

```javascript
{
    module: "MMM-Entur-tavle",
    position: "top_right",
    config: {
        stopId: '58366',
        stopType: 'StopPlace',
        numResults: 5,
        showName: true,
        highlightRealtime: true,
        delay: [5, 'minutes'],
        exclusions: [ 'a1', 'a2, 'a3' ],

    }
},
```

There is a comma after the final "exclusions" option. As this is the last option in the example given it should not have a comma at the end. The line break after exclusions will (probably) not throw a config error, but could also be considered for removal:

```javascript
{
    module: "MMM-Entur-tavle",
    position: "top_right",
    config: {
        stopId: '58366',
        stopType: 'StopPlace',
        numResults: 5,
        showName: true,
        highlightRealtime: true,
        delay: [5, 'minutes'],
        exclusions: [ 'a1', 'a2, 'a3' ]
    }
},
```

The current example may cause confusion by throwing a config error if used when testing.

(Otherwise great module and good work, thanks!)

**Comment by ThomasSjovold** [comment]
Is this Module still active and working?

**Comment by alistairspalding** [comment]
I have it running on a raspberry pi at the moment :) 

However I am not the module creator and do not know what support it has for the future. The Entur API is well supported, so that's a good sign.

**Comment by ThomasSjovold** [comment]
Thank you for the answer. That gives me hope that I'll get it up too.
I'm getting a black screen when I add the module. This is my config:
    module: "MMM-Entur-tavle",
    position: "top_right",
    config: {
        stopId: '58366',
        stopType: 'StopPlace',
        numResults: 5,
        showName: true,
        highlightRealtime: true,
        delay: [5, 'minutes'],
        exclusions: [ 'a1', 'a2,', 'a3']

this is what the error says:
[18.11.2021 23:00.35.547] [ERROR] Error: Cannot find module 'request'
Require stack:
- /home/pi/MagicMirror/modules/MMM-Entur-tavle/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Entur-tavle/node_helper.js:2:15)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pi/MagicMirror/modules/MMM-Entur-tavle/node_helper.js',
    '/home/pi/MagicMirror/js/app.js',
    '/home/pi/MagicMirror/js/electron.js',
    '/home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js',
    undefined
  ]

**Comment by ThomasSjovold** [comment]
After a lookup in the Read Me I changed to Quay:

{
module: "MMM-Entur-tavle",
position: "top_center",
config: {
stopId: '11843',
stopType: 'Quay',
numResults: 10,
highlightRealtime: true,
size: "large",
}
},

Still the same issue

**Comment by ThomasSjovold** [comment]
> I have it running on a raspberry pi at the moment :)
> 
> However I am not the module creator and do not know what support it has for the future. The Entur API is well supported, so that's a good sign.

Would you mind sending med your config and js. For this module? :-)

**Comment by alistairspalding** [comment]
Try pasting my exact module code into your own config as it is here, and see if that throws an error (you can edit the position of course). 

```{
    			module: "MMM-Entur-tavle",
    			position: "bottom_left",
			config: {
        			stopId: '58256',
        			stopType: 'StopPlace',
        			numResults: 5,
        			showName: true,
        			highlightRealtime: true,
        			delay: [5, 'minutes'],
        			exclusions: [ ]
    				}
		},
	```

**Comment by ThomasSjovold** [comment]
Thank you, Ali. 
It didn't work, and I'm afraid there's nothing wrong with this configuration itself, but rather the module and it's connection to the entur API or the readback function from Entur to MagicMirror.

Could you specify which version (OS) of Raspberry PI and MagicMirror you have?

**Comment by alistairspalding** [comment]
![tempFileForShare_20211127-130509](https://user-images.githubusercontent.com/5247588/143680635-ff742ef6-0077-48cb-afae-e0e872464ff7.jpg)

The module is still working and live for me.

MM"version": "2.14.0"
cat /etc/debian_version: 10.8
Revision        : a02082 (Pi 3 Model B)

The MMM-Entur-tavle is up to date (unsure which version).


Here's the start of MMM-Entur-tavle.js:

Module.register("MMM-Entur-tavle", {
    defaults: {
        ETApiUrl: "https://api.entur.io/journey-planner/v2/graphql",
        ETClientName: "MMM-Entur-tavle",
        stopId: "12345",
        stopType: "StopPlace", // StopPlace or Quay - case sensitive.
        numResults: 5,
        authorityId: "NSR",
        highlightRealtime: false,
        showHeader: true,
        updateSpeed: 1000,
        size: "medium",
        refresh: 30,
        showTransportMode: false,
        timeOffset: [ 0, "seconds"],
        exclusions: [],
    },


I haven't made any changes here.

**Comment by ThomasSjovold** [comment]
Thank you sir @alistairspalding! I can definitely tell a different between our Versions. Both on the model of the RPI and version of MM. I'll do some further investigating and troubleshooting this week and will update my findings here.

Thanks for sharing your information :-)
