### ISSUE TITLE
Black screen after addig module

### ISSUE THREAD

**Issue by ThomasSjovold** [Arve/MMM-Entur-tavle#15]
Hello,

I've recently added the module and added this to the config.js:
{
module: "MMM-Entur-tavle",
position: "top_center",
config: {
stopId: '11843',
stopType: 'Quay',
numResults: 10,
highlightRealtime: true,
size: "large",
}
},

When  "Npm run" it launches but stops with a black screen.

Here's the Error I get
[18.11.2021 23:55.07.832] [ERROR] WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module 'request'
Require stack:
- /home/pi/MagicMirror/modules/MMM-Entur-tavle/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
-

**Comment by Sirstyle82** [comment]
Same as I get, it would be nice if someone could answer what the problem is

**Comment by Asheluna** [comment]
> Same as I get, it would be nice if someone could answer what the problem is

This module depends on the node module called "request". If this is not installed, the MMM module fails to run.
I had to run this inside the folder "MMM-Entur-tavle": sudo npm install request

**Comment by ThomasSjovold** [comment]
Hmm, I’ll try to understand What you mean by running it inside the folder? Can you try to explain a bit more? Im new on MM.

**Comment by ThomasSjovold** [comment]
> > Same as I get, it would be nice if someone could answer what the problem is
> 
> This module depends on the node module called "request". If this is not installed, the MMM module fails to run. I had to run this inside the folder "MMM-Entur-tavle": sudo npm install request

Answered over

**Comment by Asheluna** [comment]
> > > Same as I get, it would be nice if someone could answer what the problem is
> > 
> > 
> > This module depends on the node module called "request". If this is not installed, the MMM module fails to run. I had to run this inside the folder "MMM-Entur-tavle": sudo npm install request
> 
> Answered over

I'm on Linux and in the terminal, cd into your MagicMirror/modules/MMM-Entur-tavle and there run the command "sudo npm install request". You probably not even need to use "sudo".

**Comment by Arve** [comment]
@ThomasSjovold : MagicMirror used to include the `request` node module by default, but has since switched to using `node-fetch` since request is deprecated and  no longer maintained.

MMM-Entur-tavle has largely not been maintained for a few years, but I'll issue an fix to instead use node-fetch in a few days.

**Comment by Arve** [comment]
#c651769 fixes this issue - @ThomasSjovold if you try to do a `git pull` on your MMM-Entur-Tavle and restart MagicMirror, this issue should now be fixed
