### ISSUE TITLE
error in view

### ISSUE THREAD

**Issue by rogerbl** [Arve/MMM-Entur-tavle#18]
The config below give me the correct data for the Quay, but not for the StopPlace, can you help me here?
{
                  module: "MMM-Entur-tavle",
                  position: "top_right",
                  config: {
                  stopId: '97773',
                  //stopid: '97772',
                  stopType: 'Quay',
                  numResults: 10,
                  showHeader: true,
                  highlightRealtime: true,
                  delay: [5, 'minutes'],
                  exclusions:  [ ],

                  }
                },
                {
                  module: "MMM-Entur-tavle",
                  position: "top_right",
                  config: {
                  //stopId: '97773',
                  stopid: '57080',
                  stopType: 'StopPlace',
                  numResults: 10,
                  showHeader: true,
                  highlightRealtime: true,
                  delay: [5, 'minutes'],
                  exclusions:  [ ],

                  }
                },

**Comment by Arve** [comment]
There is a typo in your second instance.  `stopId` is case sensitive, and second configuration uses `stopid` instead.
