### ISSUE TITLE
Journey-Planner-v2 API from Entur is end-of-life 

### ISSUE THREAD

**Issue by andtry** [Arve/MMM-Entur-tavle#21]
From our logs it seems MMM-Entur-tavle deployments are still using Journey-Planner-v2

This API is end-of-life, so please migrate to Journey-Planner-v3

old api - https://developer.entur.org/pages-journeyplanner-journeyplanner-v2
new api - https://developer.entur.org/pages-journeyplanner-journeyplanner

Andreas
Entur

**Comment by Arve** [comment]
Thank you for notifying me - it should be fixed with the latest commit (I also modified the ET-Client-Name header.
