### ISSUE TITLE
node-fetch dependency fix

### ISSUE THREAD

**Issue by asbjaare** [Arve/MMM-Entur-tavle#23]
Hi, MagicMirror removed the node-fetch dependency in [v2.25.0](https://github.com/MichMich/MagicMirror/releases/tag/v2.25.0) in favor of a internal fetch.

To fix just remove this line in the node_helpers.js:
`const fetch = require("node-fetch");`
https://github.com/Arve/MMM-Entur-tavle/blob/8556f01e90ab8f1e891149df6c4fc5a8f838b28e/node_helper.js#L3C4-L3C4

**Comment by veggabo** [comment]
> Hi, MagicMirror removed the node-fetch dependency in [v2.25.0](https://github.com/MichMich/MagicMirror/releases/tag/v2.25.0) in favor of a internal fetch.
> 
> To fix just remove this line in the node_helpers.js: `const fetch = require("node-fetch");` https://github.com/Arve/MMM-Entur-tavle/blob/8556f01e90ab8f1e891149df6c4fc5a8f838b28e/node_helper.js#L3C4-L3C4

Wonderful, thanks for the help!

**Comment by KristjanESPERANTO** [comment]
PR #26 fixed that. This issue can be closed :slightly_smiling_face:
