### ISSUE TITLE
Wrong time 

### ISSUE THREAD

**Issue by SvenGren** [Arve/MMM-Entur-tavle#27]
New to magicmirror and installed En tur.
Had some difficulties with wrong time in default clock module, but manage to fix that. But En tur still shows departures already left by one hour. Any solution to this?

**Comment by SvenGren** [comment]
Forget about that. System clock in Raspberry Pi was at the wrong timezone, haha.
Now it work with correct time for departures.
Merry Christmas!

**Comment by Arve** [comment]
No problem.  Merry Christmas!
