### ISSUE TITLE
Stuck at loading

### ISSUE THREAD

**Issue by amomat** [Arve/MMM-Entur-tavle#3]
Hi

Guessing I am doing something wrong here but cant understand what. Hope that I am able to get some help. When I try the example code it works fine. But when I find my bus stop (Maritim) and ender either stopPlace id 6463 or Quay 11880 it is just stuck at loading and wont show anything. Changing the stopPlace id to 58366 for Jernbanetorget works though. 

Trying this:

{
    module: "MMM-Entur-tavle",
    position: "top_left",
    config: {
        stopId: '6463',
        stopType: 'StopPlace',
        numResults: 5,
        showName: true,
        highlightRealtime: true,
        size: 'small'
    }
},

And this:

{
    module: "MMM-Entur-tavle",
    position: "top_left",
    config: {
        stopId: '11880',
        stopType: 'Quay',
        numResults: 5,
        showName: true,
        highlightRealtime: true,
        size: 'small'
    }
},

Could anyone please take a look at it and see what I am doing wrong?

This works though:

{
    module: "MMM-Entur-tavle",
    position: "top_left",
    config: {
        stopId: '58366',
        stopType: 'StopPlace',
        numResults: 5,
        showName: true,
        highlightRealtime: true,
        size: 'small'
    }
},

Thanks

**Comment by Arve** [comment]
I just tried this, and am getting proper results (Assuming routes 24,31 and 32 are passing this stopPlace).
 
                        config: {
                                stopId: "11880",
                                stopType: "Quay",
                                highlightRealtime: true,
                                size: "small",
                                numResults: 6,
                                showName: true,
                        }

Would you mind trying again, and see if it's working again (There might have been some error on Entur's backend?   If it's still not working, could you run MagicMirror in serveronly mode, and post the output in the console and in the terminal?

**Comment by amomat** [comment]
Was out the entire day and when I came back it was all working. Spent 3h trying to fix it the other day. Maybe something with Entur or maybe something with my internet. Works now anyway. Thanks for the help and thanks for the module. Really nice to have now that Ruter api will stop work.

**Comment by Arve** [comment]
No problem. Hope you'll continue enjoying it.

**Comment by amomat** [comment]
Hi again. Seems like there still is something wrong. Had it going now for a couple of weeks and it updates only at random. When I restart MM it can take an hour before it loads. And then it just updates a couple of times a day. Been playing around with refresh without any luck. Getting an error when I load MM in a browser:

Uncaught (in promise) ReferenceError: $this is not defined
    at Class.getDepartureTime (MMM-Entur-tavle.js:104)
    at Class.getDom (MMM-Entur-tavle.js:78)
    at main.js:110
    at new Promise (<anonymous>)
    at updateDom (main.js:109)
    at Object.updateDom (main.js:514)
    at Class.updateDom (module.js:358)
    at Class.socketNotificationReceived (MMM-Entur-tavle.js:92)
    at module.js:246
    at r.<anonymous> (socketclient.js:25)

Current config input:

		{
			module: "MMM-Entur-tavle",
			position: "top_left",
			header: "Maritim",
			config: {
				stopId: "11880",
				stopType: "Quay",
				highlightRealtime: true,
				size: "small",
				numResults: 6,
				showName: true,
				refresh: 240
			}
		},

Do you have any tips or ideas on what I can try?

**Comment by Arve** [comment]
First off, there's an error in your config (that I missed the last time around, because I was in a hurry):

    showName: true,

should instead read:

    showHeader true,

... after which you can remove `header: "Maritim",` from your config file, as it will pull it directly from the queried data.

As for your error: I've been running it with several months of uptime on both a Raspberry Pi 3 and a MacOS box, both running in serveronly mode, or in regular mode, and have never had an issue with it, so I'm a bit at a loss as to why it's happening.

I'll have a look at it over the weekend, and may prepare a version with some extended logging of what's going on, so we can see what's happening
