### ISSUE TITLE
Feature request: Set lower threshold to hide entries with less than 10 minutes to departure

### ISSUE THREAD

**Issue by thomasberglund** [Arve/MMM-Entur-tavle#5]
Hi. First of all, great job making this module! I really like it.

I have a feature request. I would like to be able to set a lower threshold to hide entries with less than e.g. 10 minutes to departure. For a lot of people, there is no point in seeing departures with less then 5-10 minutes to departure, simply because the distance between home and public transport is longer than a 5 minute walk away :)

**Comment by EldarAron** [comment]
Or maybe add walking/travel distance? If it takes 5 minutes to walk to the stop. Then the entries should get 5 minutes added. So if the bus leaves 15:07. Then the entry should say 15:02. When it changes to minutes until departure, it should include the 5 minutes. So when it says 0 minutes you have 5 minutes to get to the stop.

**Comment by Arve** [comment]
Adding walking distance is a bit of a no-no, as it'd have to query a few different APIs.  I'm working on another project with what amounts to a deadline, but I'll try to add the timeout sometimes toward the end of this week or at the beginning of next.

**Comment by EldarAron** [comment]
I was more thing of just simple hack of deducting  x minutes to the results that we get back from the API.

Let's say I use 5 minutes to walk to the bus stop. Let's say that the bus arrives at the stop at 15:25 when queering the API. Then take the time I have configured to walk to the stop; 5 min, and deduct that from the arrival time of the bus. The new time shown is 15:20. When it's less then 10 minutes to new time. it shows the minutes until I have to leave. If I leave at 15:20, I'll get bust at 15:25.

**Comment by Arve** [comment]
This is now fixed.  While I can't accomodate things such as 'walking distance (because MagicMirror doesn't actually know where you are physically, and I'm not about to hack geolocation), there is a new config value: 'timeOffset' that should serve you well:

```js 
{
  /* rest of config */
  timeoffset: [10, 'minutes']
}
```

will only load departures that are further than  10 minutes from now.
