### ISSUE TITLE
Feature request: Add filter on line number(s)

### ISSUE THREAD

**Issue by EldarAron** [Arve/MMM-Entur-tavle#7]
Hello
Really love your module. Would be nice to filter on line number(s) also not just platforms. A lot of lines terminate on my platform  (16804). So I get a lot of "junk" on my screen.
Keep up the good work! :)
//Eldar Aron

**Comment by Arve** [comment]
If you live at an endpoint, you will probably want to query for a specific quay instead of a stop.  That said, I should be able to fix this at the same time I get around to fixing the minimum timeout feature.

**Comment by EldarAron** [comment]
Sorry for not expressing myself clear enough. That is a platform(quay id) on Drammen bus station. A lot of lines terminate at the same platform as some start from.

ok, thanks! Can't be more pleased. I'm not good at coding.

**Comment by Arve** [comment]
Fixed.
