### ISSUE TITLE
Black screen after latest update

### ISSUE THREAD

**Issue by veggabo** [Arve/MMM-Entur-tavle#9]
After I updated to the latest commit, my MagicMirror turned black. When I deactivate this module using /* */, my mirror is back to normal (except for lacking data from this module, naturally). Is it something wrong in my config setup below, or is it something else that may cause this?

{
                        module: "MMM-Entur-tavle",
                        position: "bottom_center",
                        config: {
                                stopId: '10851',
                                stopType: 'Quay',
                                numResults: 10,
                                highlightRealtime: true,
                                size: "large",
                        }
},

**Comment by Arve** [comment]
It should be working now - I forgot to rename a lookup value for one of the new configuration settings, so the script errored when it couldn't find the setting

**Comment by ThomasSjovold** [comment]
I'm experiencing this now! Any fix?
